services:
  api1:
    image: ghcr.io/krymancer/rinha-de-backend-2026-zig:bfb7c651bcaab585d0ced7c5db4600e6ce80feef
    command: ["/api", "/sockets/api1.sock", "/index.bin", "0", "40"]
    network_mode: none
    cpuset: "0"
    volumes:
      - sockets:/sockets
    ulimits:
      memlock: -1
      nofile: { soft: 65535, hard: 65535 }
    deploy:
      resources:
        limits:
          cpus: "0.44"
          memory: "169MB"

  api2:
    image: ghcr.io/krymancer/rinha-de-backend-2026-zig:bfb7c651bcaab585d0ced7c5db4600e6ce80feef
    command: ["/api", "/sockets/api2.sock", "/index.bin", "0", "40"]
    network_mode: none
    cpuset: "1"
    volumes:
      - sockets:/sockets
    ulimits:
      memlock: -1
      nofile: { soft: 65535, hard: 65535 }
    deploy:
      resources:
        limits:
          cpus: "0.44"
          memory: "169MB"

  lb:
    image: ghcr.io/krymancer/rinha-de-backend-2026-zig:bfb7c651bcaab585d0ced7c5db4600e6ce80feef
    command: ["/lb", "9999", "/sockets/api1.sock", "/sockets/api2.sock"]
    depends_on:
      - api1
      - api2
    cpuset: "2,3"
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    ulimits:
      nofile: { soft: 65535, hard: 65535 }
    deploy:
      resources:
        limits:
          cpus: "0.12"
          memory: "8MB"

volumes:
  sockets:
    driver_opts:
      type: tmpfs
      device: tmpfs
